services:
  - type: web
    name: materias-aviso-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python materias.py
    healthCheckPath: /healthcheck
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.0
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
